aplicacion/atrium/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/email_available/check', 'ClientController@check')->name('email_available.check');
Route::get('/locale/{locale}', function ($locale) {
    Session::put('locale',$locale);
    return redirect()->back();
})->name('locale');

Route::get('confirm/later/{ConfirmationCode}','DashboardController@confirmWithOutFix')->name('confirm.later');
#https://www.atriumprivatebanker.com

Auth::routes(['verify'=>true]);
Route::get('/home','DashboardController@index')->name('dash.user_approbe')->middleware(['auth'],['verified']);
Route::get('/','DashboardController@index')->name('dash.user_approbe')->middleware(['auth'],['verified']);

Route::get('client/delete/{id}', 'DashboardController@delete')->name('client.delete')->middleware(['auth']);

Route::get('dash/user','DashboardController@index')->name('dash.user_approbe')->middleware('auth');
Route::get('register/user','DashboardController@register')->name('register.user')->middleware('auth');
Route::post('store/user','DashboardController@storeUser')->name('store.user');
Route::post('approve','DashboardController@approve')->name('approve')->middleware('auth');
Route::post('/approveTransaction','DashboardController@approveTransaction')->name('approveTransaction')->middleware('auth');
Route::post('/denyTransaction','DashboardController@denyTransaction')->name('denyTransaction')->middleware('auth');

Route::post('deny','DashboardController@deny')->name('deny')->middleware('auth');
Route::post('client/details','DashboardController@detailClient')->name('client.detail')->middleware('auth');
Route::post('client/getClient','DashboardController@getClient')->name('client.getClient')->middleware('auth');
Route::post('client/getCoinPercentaje','DashboardController@getCoinPercentaje')->name('client.getCoinPercentaje')->middleware('auth');

Route::get('coin','CoinController@index')->name('coin.list')->middleware('auth');
Route::post('coin','CoinController@store')->name('store.coin')->middleware('auth');
Route::post('coinUpdate','CoinController@update')->name('update.coin')->middleware('auth');
Route::post('getCoin','CoinController@getCoin')->name('coin.getCoin')->middleware('auth');
Route::post('available','CoinController@available')->name('coin.available')->middleware('auth');
Route::post('saveBuyUser','CoinController@saveBuyUser')->name('coin.saveBuyUser')->middleware('auth');
Route::post('sendConfirmMail','DashboardController@sendConfirmMail')->name('sendConfirmMail')->middleware('auth');


Route::get('sign','DashboardController@registerWithOutAutenticate')->name('register.withOutLogin');
Route::post('state/get','CountryController@getState')->name('get.State');
//Route::post('city/get','CountryController@getCity')->name('get.City');
Route::post('city/get/withOutState','CountryController@getCityWithOutState')->name('get.CityWithOutState');


Route::get('/autocomplete/fetch', 'CountryController@fetch')->name('autocomplete.fetch');
Route::get('/autocomplete/city/fetch', 'CountryController@fetchCity')->name('autocomplete.fetch.city');


Route::get('/test', 'DashboardController@test')->name('test');

Route::get('/register/verify/{code}', 'ClientController@verify');

Route::get('/login','Auth\ClientLoginController@showLoginForm')->name('login');

Route::post('/login', 'Auth\ClientLoginController@login')->name('client.login.submit');
Route::post('/logout', 'Auth\ClientLoginController@logout')->name('logout');

Route::group(['prefix'=>'client','middleware' => 'auth:customusers'], function() {
    Route::get('/', 'ClientController@index')->name('client.dashboard');
    Route::get('/buyer/{coin_id?}', 'ClientController@buyer')->name('client.buyer');
    Route::post('/buy', 'ClientController@buy')->name('client.buy');
    Route::get('/settings', 'ClientController@settings')->name('client.settings');
    Route::get('/profile/account', 'ClientController@profileAccount')->name('client.account');
    Route::post('/secondPassword','ClientController@sendRecoverySecondPassword')->name('sendRecoverySecondPassword');

//payment form
Route::get('/payment', 'PaymentController@index');
// route for processing payment
Route::post('paypal', 'PaymentController@payWithpaypal')->name('client.paypal');
// route for check status of the payment
Route::get('status', 'PaymentController@getPaymentStatus')->name('status');

});

aplicacion/atrium/app/Models/Movement.php
<?php

namespace App\Models;
use Event;
use Log;
use Illuminate\Database\Eloquent\Model;

class Movement extends Model
{

    protected $table = "movements";
    protected $dates = ["date_approve","date_movement"];
    protected $fillable =[
        'client_id',
        'coin_id',
        'method_payment_id',
        'quantity',
        'price_actually',
        'date_approve',
        'date_deny',
        'date_movement',
        'state',
        'observation'
    ];

    /*public static function boot(){
        parent::boot();
        static::created(function($movement){
            Log::info("sendMail");
            Event::fire('createdMovement',$movement);
        });
    }*/
    public function coin(){
        return $this->belongsTo('\App\Models\Coin','coin_id','id');

    }

    public function methodPayment(){
        return $this->belongsTo('\App\Models\MethodPayment','method_payment_id','id');

    }

    public function client(){
        return $this->belongsTo('\App\Models\Client','client_id','id');

    }

    public function getStatedAttribute(){
       $txt="";
        switch ($this->state) {
            case 'P':
               $txt='Pending';  
                break;
            case 'A':
               $txt='Authorized';  
                break;    
            case 'I':
		$txt='Declined';
                break; 
            default:
                $txt="Revisar";
                break;
        }

        return $txt;
    }


    public function getValorAttribute(){
       
        
        return number_format($this->quantity*$this->price_actually,2);
    }




}

aplicacion/atrium/app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;
use App\Models\Client;
use App\Models\AccountBank;
use App\Models\Country;
use App\Models\Coin;
use App\Models\State;
use App\Mail\approve;
use App\Models\City;
use App\Models\Movement;
use Illuminate\Http\Request;
use Redirect;
use Auth;
use Illuminate\Support\Arr;
use App\Notifications\clients;
use App\Mail\demoMail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Keygen;
use GuzzleHttp;
use App\Jobs\NewBuyerEmail;
use App\Jobs\AprobarTranferencia;
use App\Jobs\DenegarTranferencia;
use Log;
use DB;

class DashboardController extends Controller
{
    public function index(){
    	$clients = Client::where('state','A')->whereNull('Approved')->WhereNull('Deny')->paginate(15);
        $movements = Movement::where('state','P')->paginate(15);

	return view('dashboard.index', compact('clients', 'clientsAprobe', 'movements'));
    }
    public function register(){
    	$clients = Client::where('state','A')->whereNotNull('Approved')->paginate(15);
        $coins = Coin::all();
    	return view('dashboard.register2', compact('clients','coins'));
    }

    public function registerWithOutAutenticate(){
        return view('dashboard.registerWithOutAutenticate');
    }

    public function test(){
        $movement = Movement::find(135);
        $client = Client::all()->first();
         
        return view('mails.layaout', compact('movement', 'client'));
       /*

 $clients = \App\Models\Client::where('state','A')->where('Confirmed',0)->get();

        foreach($clients as  $client){
            try {
                Mail::to($client->Email)->send(new demoMail($client));        
            } catch (\Exception $e) {
                Log::info($e->getMessage());
            }
         
        }



       $a = DB::select("select * from Ciudades where Paises_Codigo='CO'");

        foreach ($a as $ciudades){
            $miciudad = DB::select("select * from cities where upper(name)='".$ciudades->Ciudad."' limit 1");
            if($miciudad!=null){
                $mipais = DB::select("select * from Paises where Codigo='".$ciudades->Paises_Codigo."' limit 1");
                if(!$mipais!=null){
                    echo "esta ciudad :".$ciudades->Ciudad." pero en otro pais:".$ciudades->Codigo."<br>";
                }
            }else{
                $mipais = DB::select("select * from Paises where Codigo='".$ciudades->Paises_Codigo."' limit 1");
                echo "la ciudad: ".$ciudades->Ciudad." no se encuentra en la bd PAIS: ".$mipais[0]->Pais."<br>";
            }
        }

        
        $client = new GuzzleHttp\Client();

        $abcdario = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];

        $res = $client->get('https://en.wikipedia.org/wiki/List_of_towns_and_cities_with_100,000_or_more_inhabitants/cityname:_A');
        
        echo $res->getBody()->getContents();
       */
    }

    public function storeUser(Request $req){

        if($req->ajax()){
            $arr = $req->all();
            Log::info(json_encode($arr));
            $client = new Client();
            $client->FirstName=!isset($req->FirstName) || is_null($req->FirstName)? null:$req->FirstName;            
            $client->LastName=!isset($req->LastName) || is_null($req->LastName)? null:$req->LastName;         
            $client->Email=!isset($req->Email) || is_null($req->Email)? null:$req->Email;      
            $client->Password=\Bcrypt($req->password);
            $client->SecondPassword=\Bcrypt($req->password_2);
            
            $client->UserName_NDG=$this->generateCode();
            $client->ManagerId_NDG=$this->generateCode();
            $client->BirthDate=!isset($req->BirthDate) || is_null($req->BirthDate) || !$this->validateDate($req->BirthDate)? null:$req->BirthDate;        
            $client->CountryBirth=!isset($req->CountryBirth) || is_null($req->CountryBirth)? null:$req->CountryBirth;         
            $client->DistrictBirth=!isset($req->DistrictBirth) || is_null($req->DistrictBirth)? null:$req->DistrictBirth;            
            $client->CityBirth=!isset($req->CityBirth) || is_null($req->CityBirth)? null:$req->CityBirth;            
            $client->CountryResidency=!isset($req->CountryResidency) || is_null($req->CountryResidency)? null:$req->CountryResidency;
            $client->Address=!isset($req->Address) || is_null($req->Address)? null:$req->Address;  
            $client->CertificationResidency=!isset($req->CertificationResidency) || is_null($req->CertificationResidency)? null:$req->CertificationResidency;           
            $client->DocumentType=!isset($req->DocumentType) || is_null($req->DocumentType)? null:$req->DocumentType;
            $client->DocumentIdentification=!isset($req->DocumentIdentification) || is_null($req->DocumentIdentification)? null:$req->DocumentIdentification;
            $client->DocumentIssueDate=!isset($req->DocumentIssueDate) || is_null($req->DocumentIssueDate) || !$this->validateDate($req->DocumentIssueDate)? null:$req->DocumentIssueDate;
            $client->DocumentexpirationDate=!isset($req->DocumentexpirationDate) || is_null($req->DocumentexpirationDate) || !$this->validateDate($req->DocumentexpirationDate)? null:$req->DocumentexpirationDate;
            $client->ConfirmationCode= Keygen::token(38)->generate();
            try {
                $client->save();
            } catch (Exception $e) {
                Log::info("error: ".$e->getMessage());
                return json_encode(['state'=>500, 'msj'=>$e->getMessage()]);
            }
            Log::info("succe:".$client->UserName_NDG.'identy:'.$client->id );
            return json_encode(['state'=>200 ,'msj'=>'guardado','code'=>$client->UserName_NDG,'identy'=>$client->id]);
        }

        if($req->identy){
            
            $cl = Client::find($req->identy);

            $cl->confirmed = true;
            $cl->ConfirmationCode = null;
            
            $cl->DocumentType=!isset($req->DocumentType) || is_null($req->DocumentType)? null:$req->DocumentType;
            $cl->DocumentIdentification=!isset($req->DocumentIdentification) || is_null($req->DocumentIdentification)? null:$req->DocumentIdentification;
            $cl->DocumentIssueDate=!isset($req->DocumentIssueDate) || is_null($req->DocumentIssueDate)? null:$req->DocumentIssueDate;
            $cl->DocumentexpirationDate=!isset($req->DocumentexpirationDate) || is_null($req->DocumentexpirationDate)? null:$req->DocumentexpirationDate;
            $cl->CertificationResidency=!isset($req->CertificationResidency) || is_null($req->CertificationResidency)? null:$req->CertificationResidency;
            $cl->DocumentImage=!isset($req->DocumentImage) || is_null($req->DocumentImage)? null:$req->DocumentImage;
            $cl->NumberCard=!isset($req->NumberCard) || is_null($req->NumberCard)? null:$req->NumberCard;           
            try{
                $cl->save();
            }catch(Exception $e){
                return back()->withInput()->withErrors([$e->getMessage()]);

            }

            if(isset($req->EthereumWallet) && !is_null($req->EthereumWallet)){
                $acc = new AccountBank();

                $acc->client_id = $cl->id;
                $acc->EthereumWallet=!isset($req->EthereumWallet) || is_null($req->EthereumWallet)? null:$req->EthereumWallet;
                $acc->IBAN=!isset($req->IBAN) || is_null($req->IBAN)? null:$req->IBAN;
                $acc->HeaderAccount=!isset($req->HeaderAccount) || is_null($req->HeaderAccount)? null:$req->HeaderAccount;
                $acc->BankAccount=!isset($req->BankAccount) || is_null($req->BankAccount)? null:$req->BankAccount;
                $acc->SwiftCode=!isset($req->SwiftCode) || is_null($req->SwiftCode)? null:$req->SwiftCode;
                $acc->Prefered=!isset($req->Prefered) || is_null($req->Prefered)? null:'S';

                try{
                    $acc->save();
                }catch(Exception $e){
                    Log::info($e->getMessage());
                    return back()->withInput()->withErrors([$e->getMessage()]);

                }
            }


            return Redirect()->route('login')->withSuccess('Register Completed');


        }
/*
    	try {
            $peticion = $req->all();
            $peticion['UserName_NDG']=str_shuffle('dasdgqwgq');
            $peticion['CountryResidency']=1;
            $peticion['Address']='Mi Direccion';
            Client::create($peticion);
    	} catch (\Exception $e) {
    		return back()->withInput()->withErrors([$e->getMessage()]);
    	}


*/
    	return Redirect()->route('dash.user_approbe')->withSuccess('Done User');
    }

    public function approve(Request $req){
        try {
            
            $client = Client::find($req->clientId);
            if(is_null($client)){
                return json_encode(['msj'=>'No Existe Cliente','state'=>500]);    
            }
            if(!is_null($client->Deny)){
                return json_encode(['msj'=>'Este Cliente ya fue Denegado','state'=>500]);
            }
            $client->Approved=\Carbon\Carbon::now();
            $client->ApprovedBy=Auth::user()->id;
            $client->save();
        

        try {
               Mail::to($client->Email)->send(new approve($client)); 
        } catch (\Exception $e) {
                Log::info($e->getMessage());
               return json_encode(['msj'=>$e->getMessage(),'state'=>500]);    
        }

            
   
        } catch (\Exception $e) {
            Log::info($e->getMessage());
            return json_encode(['msj'=>$e->getMessage(),'state'=>500]);   
        }

        return json_encode(['msj'=>'Approved','state'=>200]);
    }


    public function approveTransaction(Request $req){
        try {
            DB::beginTransaction();
            $mov = Movement::find($req->movId);
            if($mov->state=='A'){

aplicacion/atrium/resources/views/dashboard/clientDetails.blade.php
@extends('layout.atrium')
@section('css-atrium')
    <style>
        .disabled{
            color: #b9afaf;
        }
        .disabledbtn , .disabledbtn2{
            background: #b9afaf !important;
            color: white !important;
            border-color: rgba(44,129,212,.25) !important;
        }
    </style>
@endsection

@section('container')
    <div class="col-md-7 col-xl-10 pr-3">
        <div class="card">
        <div class="card-body">
            <div class="cp" style="padding: 24px 29px 33px 43px;">
 
            <div class="row">
                <div class="col-md-1 text-right">
                    <label>Client</label>
                </div>
                <div class="col-md-2 text-left">
                    <label><strong>{{$client->FirstName .' '.$client->LastName}}</strong></label>
                </div>
                <div class="col-md-1 text-right">
                    <label>Email</label>
                </div>
                <div class="col-md-3 text-left">
                    <label><strong>{{$client->Email}}</strong></label>
                </div>
                <div class="col-md-2 text-right">
                    <label>Date Register</label>
                </div>
                <div class="col-md-1 text-left">
                    <label><strong>{{$client->created_at->format('Y.m.d')}}</strong></label>
                </div>
            </div>

            <label>Moviments</label>
               
            <div class="row" style="margin-top:10px;">
               <div class="table-responsive">
               <table class="table">
                 <thead>
                        <th>Coin</th>
                        <th>Quantity</th>
                        <th>Price Seld</th>
                        <th>State</th>
                        <th>Observation</th>
                        <th>Date Movement</th>
                 </thead>
                 <tbody>
                   @if(count($client->Movements)>0)
                    @foreach($client->Movements as $value)
                      <tr>
                        <td>{{$value->coin->name}}</td>
                        <td>{{$value->quantity}}</td>
                        <td>{{$value->price_actually}}</td>
                        <td>{{$value->stated}}</td>
                        <td>{{$value->observation}}</td>
                        <td>{{$value->created_at->format('Y.m.d')}}</td>
                      </tr>
                    @endforeach
                   @else
                    <tr><td colspan="6" class="text-center" >Not Movements Client  </td> </tr>
                   @endif 
                 </tbody>
              </table>
              </div>
            </div>
            </div>
            </div>   
        </div>
        </div>

@endsection         
@section('js-atrium')
    @include('error.error')
<script type="text/javascript">
</script>
@endsection

aplicacion/atrium/resources/views/dashboard/register.blade.php
@extends('layout.atrium')
@section('container')
<div class="col-md-7 col-xl-10 pr-3">
              <div class="card">

                <div class="card-body">
                  <h4>Register</h4>
                  <div class="cp">
                    <form action="{{route('store.user')}}" method="POST">
                    {{ csrf_field() }}
                    <div class="form-group">
                      <label>Atrium ID:</label>
                      <input
                        type="text"
                        class="form-control"
                        id="atriumID"
                        placeholder="Atrium ID"
                        name="UserName_NDG"
                        value="{{ old('UserName_NDG') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Email address</label>
                      <input
                        type="email"
                        class="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Enter email"
                        name="Email"
                        value="{{ old('Email') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label>Nombres</label>
                      <input
                        type="text"
                        class="form-control"
                        id="nombres"
                        placeholder="Nombres"
                        name="FirstName"
                        value="{{ old('FirstName') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label>Apellidos</label>
                      <input
                        type="text"
                        class="form-control"
                        id="apellidos"
                        placeholder="Apellidos"
                        name="LastName"
                        value="{{ old('LastName') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label for="formGroupExampleInput"
                        >Fecha de nacimiento</label
                      >
                      <input
                        type="date"
                        class="form-control"
                        id="fechaNac"
                        placeholder="10-02-1989"
                        name="BirthDate"
                        value="{{ old('BirthDate') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label for="inputCountry">País de nacimiento</label>
                      <select id="inputCountry" class="form-control" name="CountryBirth" value="{{ old('CountryBirth') }}">
                        <option selected>Choose...</option>
                        <option value="1">1</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="inputState">State</label>
                      <select id="inputState" class="form-control" name="DistrictBirth" value="{{ old('DistrictBirth') }}">
                        <option selected>Choose...</option>
                        <option value="1">1</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="inputCity">Ciudad de nacimiento</label>
                      <select id="inputCity" class="form-control" name="CityBirth" value="{{ old('CityBirth') }}">
                        <option selected>Choose...</option>
                        <option value="1">1</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="inputCountryR">País de residencia</label>
                      <select id="inputCountryR" class="form-control" name="CountryResidency" value="{{ old('CountryResidency') }}">
                        <option selected>Choose...</option>
                        <option value="1">1</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label>Direccion</label>
                      <input
                        type="text"
                        class="form-control"
                        id="dir"
                        placeholder="Direccion"
                        name="Address"
                        value="{{ old('Address') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label for="tipoDoc">Tipo de documento</label>
                      <select id="tipoDoc" class="form-control" name="DocumentType" value="{{ old('DocumentType') }}">
                        <option selected>Choose...</option>
                        <option>C.C</option>
                        <option value="1">1</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label>Número de documento</label>
                      <input
                        type="text"
                        class="form-control"
                        id="numDoc"
                        placeholder="Número documento"
                        name="DocumentIdentification"
                        value="{{ old('DocumentIdentification') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label for="formGroupExampleInput"
                        >Fecha de erogación</label
                      >
                      <input
                        type="date"
                        class="form-control"
                        id="fechaDocE"
                        placeholder="10-02-1989"
                        name="DocumentIssueDate"
                        value="{{ old('DocumentIssueDate') }}"
                      />
                    </div>
                    <div class="form-group">
                      <label for="formGroupExampleInput"
                        >Fecha de vencimiento</label
                      >
                      <input
                        type="date"
                        class="form-control"
                        id="fechaVen"
                        placeholder="10-02-1989"
                        name="DocumentexpirationDate"
                        value="{{ old('DocumentexpirationDate') }}"
                      />
                    </div>

                    <div class="form-group">
                      <div class="custom-file">
                        <input
                          type="file"
                          class="custom-file-input"
                          id="validatedCustomFile"
                          required
                          name="CertificationResidency"
                        />
                        <label
                          class="custom-file-label"
                          for="validatedCustomFile"
                          >Choose file...</label
                        >
                        <div class="invalid-feedback">
                          Example invalid custom file feedback
                        </div>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="custom-file">
                        <input
                          type="file"
                          class="custom-file-input"
                          id="validatedCustomFile2"
                         name="DocumentImage"
                        />
                        <label
                          class="custom-file-label"
                          for="validatedCustomFile2"
                          >Choose file...</label
                        >
                        <div class="invalid-feedback">
                          Example invalid custom file feedback
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary">
                      Submit
                    </button>
                  </form>
                    
                  </div>
                </div>
              </div>
            </div>

@endsection

aplicacion/atrium/resources/views/dashboard/user_aprove.blade.php
@extends('layout.master')
@section('container')
<!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    

    <!-- Main content -->
    <section class="content">
     <div class="col-lg-12 col-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Customtab vertical Tab</h3>
              <h6 class="box-subtitle">Use default tab with class <code>vtabs, tabs-vertical & customvtab</code></h6>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
            	<!-- Nav tabs -->
				<div class="vtabs customvtab">
					<ul class="nav nav-tabs tabs-vertical" role="tablist">
						<li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home3" role="tab" aria-expanded="true"><span class="hidden-sm-up"><i class="ion-home"></i></span> <span class="hidden-xs-down">Home</span> </a> </li>
						<li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile3" role="tab" aria-expanded="false"><span class="hidden-sm-up"><i class="ion-person"></i></span> <span class="hidden-xs-down">Profile</span></a> </li>
						<li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#messages3" role="tab" aria-expanded="false"><span class="hidden-sm-up"><i class="ion-email"></i></span> <span class="hidden-xs-down">Messages</span></a> </li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content">
						<div class="tab-pane active" id="home3" role="tabpanel" aria-expanded="true">
							<div class="pad">
								<div class="table-responsive">
				  <table class="table table-hover">
					<tr>
					  <th>AtriumId</th>
					  <th>Email</th>
					  <th>Name</th>
					  <th>Date Register</th>
					  <th>Approve</th>
					  <th>Decline</th>
					</tr>
					@foreach($clients as $client)
						<tr>
						  <td><a href="javascript:void(0)">Order #123456</a></td>
						  <td>{{$client->Email}}</td>
						  <td>{{$client->FirstName.' '.$client->LastName}}</td>
						  <td><span class="text-muted"><i class="fa fa-clock-o"></i> {{$client->created_at->format('d.m.Y')}} </span> </td>
						  <td><span class="label label-info">Approve</span></td>
						  <td><span class="label label-danger">Decline</span></td>
						</tr>
					@endforeach
					
				  </table>
				</div>
							</div>
						</div>
						<div class="tab-pane pad" id="profile3" role="tabpanel" aria-expanded="false">2</div>
						<div class="tab-pane pad" id="messages3" role="tabpanel" aria-expanded="false">3</div>
					</div>
				</div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      
    </section>
    <!-- /.content -->
  
  
@endsection